### ISSUE TITLE
Scrollbar keeps focus after using scrollwheel on it

### ISSUE THREAD

**Issue by Szunti** [pgimeno/Gspot#1]
I saw this in the demo. Move the mouse onto the scrollbar, use the scrollwheel, then move the mouse out. The scrollbar is still focused.

**Comment by pgimeno** [comment]
I can reproduce this. And I've found more issues with the mouse wheel than that. If you use the mouse wheel over the "Custom goodness" window, then move the mouse around the screen and click anywhere with the LMB or RMB, the "Custom goodness" window is moved there. A similar result is obtained if using the mouse wheel over the title area of any window.

Will look into it, thanks for the report!

**Comment by pgimeno** [comment]
Well, it was easier than I thought. Can you please check out commit 2e9de10 or branch [fix-wheel-focus](https://github.com/pgimeno/Gspot/tree/fix-wheel-focus) and see if it causes no other issues? To the best of my knowledge it still works as expected, but I may have missed some corner cases.

**Comment by Szunti** [comment]
fix-wheel-focus works well as far as I can tell.

**Comment by pgimeno** [comment]
Thanks for confirming. Merged and pushed, so I'm closing this now..
