### ISSUE TITLE
Inputs don't work when text width is greater that set width

### ISSUE THREAD

**Issue by davisdude** [pgimeno/Gspot#2]
What I mean by this is that when the text goes beyond the width of the input, when you press `home` (or try to use the arrow keys), it will not bring you back to the beginning.

**Comment by pgimeno** [comment]
Thanks for the report. This is a known issue (see full description of commit 18c9eb5) but it's best to have it here to help track it.

**Comment by pgimeno** [comment]
I've pushed a fix. Please let me know if it causes more problems.
