### ISSUE TITLE
Invisible items are clickable

### ISSUE THREAD

**Issue by linux-man** [pgimeno/Gspot#5]
I found this issue when doing the loveFS dialog box, so I simplified the code:
Just click over/under the group.
```
gui = require('Gspot')

love.load = function()
	dialog = gui:group(label, {love.graphics.getWidth( )/2 - 200, love.graphics.getHeight()/2 - 200, 400, 400})
	dScrollGroup = gui:scrollgroup(nil, {0, gui.style.unit, dialog.pos.w, dialog.pos.h - gui.style.unit}, dialog, 'vertical')
	for n = 0, 40 do
		local grp = gui:group('', {0, 0, dScrollGroup.pos.w, gui.style.unit}, nil)
		local btn = gui:button('Button '..n, {0, 0, dScrollGroup.pos.w, gui.style.unit}, grp)
		btn.click = function(this)
			gui:feedback('Click on '..btn.label)
		end
		dScrollGroup:addchild(grp, 'vertical')
		dScrollGroup.scrollv.values.current = 160
	end
end
love.update = function(dt)
	gui:update(dt)
end
love.draw = function()
	gui:draw()
end
love.mousepressed = function(x, y, button)
	gui:mousepress(x, y, button)
end
love.mousereleased = function(x, y, button)
	gui:mouserelease(x, y, button)
end
```
The issue arises when clicking a child inside a child of a scrollbox (the demo has a similar situation, so it must not be that rare).
I propose to change "containspoint" to address this situation: an item only containspoint if his parents also contains:
```
containspoint = function(this, point)
		local contains = false
		local pos = point.pos or point
		if this.elementtype == 'text' then
			-- Text is treated specially, because it's drawn
			-- centered vertically without moving its position,
			-- therefore the apparent position is different from
			-- the element's pos. Size should be correct, though.
			pos.x = pos.x - math.floor((element.style.unit / 4) + 0.5)
			pos.y = pos.y - math.floor(((element.style.unit - element.style.font:getHeight()) / 2) + 0.5)
			if this.withinrect(pos, this:getpos()) then contains = true end
		else
			if this.shape == 'circle' and this.withinradius(pos, this:getpos() + this.pos.r) then contains = true
			elseif this.withinrect(pos, this:getpos()) then contains = true end
		end
		if contains and this.parent then contains = this.parent:containspoint(point) end
		return contains
	end,
```
The recursion forced me to include the text calculations. This way, the cycle at line 160 is reduced to
```
	for i = #this.elements, 1, -1 do
		local element = this.elements[i]
		if element.display then
			if element:containspoint(mouse) then
				if element.parent and element.parent:type() == 'Gspot.element.scrollgroup' and element ~= element.parent.scrollv and element ~= element.parent.scrollh then this.mousein = element break
				else this.mousein = element break end
			end
		end
	end
```
Hope to be helpful.

**Comment by pgimeno** [comment]
Thanks a lot for taking the time to write a small test case. Now I get what you meant.

Ever since I first looked at that loop (the one at line 160), I hated it. It's no good. It works mostly by chance; it relies on the fact that the children will always have a greater index than the parent, and that's a very flimsy assumption. It has caused a lot of trouble, and this bug shows just another problem with that approach.

Your fix would work, but at the cost of redundant checking. The loop would make one check for a particular element, but if it's a parent of another element, the recursion would check it again.

So, all things considered, I think that the best fix would be to get rid of the loop once and for all, substituting it with a proper depth-first traversal of the widget tree. We already have information on what a widget's children are, so it should not be too difficult.

**Comment by linux-man** [comment]
Looks like a structural change. Lots of work!
To make things worst, I really think that none of the elements should be drawn/accessible outside the parent boundaries with one exception - children of collapsegroup. Just because I'm trying to do a "load file dialog" and the extension filter combobox is usually at the bottom.

**Comment by pgimeno** [comment]
Yes, it's a structural change, and it's going to make things incompatible, or too burdensome to keep compatibility (currently, the elements array determines the drawing order, and the children array needs to do that same function, so there would be some duplication of code to maintain both arrays). I've already advanced a bit, but after some thought, I think I'm going to branch the development here, apply your suggestion or a variation of it to the current branch, and create a new one for what will eventually be Gspöt2.

Widget systems that implement comboboxes typically use a separate borderless window for the drop-down menu. That window is _not_ a child of the control, for the very reason you mention. Gspöt doesn't currently have a "keep on top" window property, which would probably be useful for the implementation of that control. That'll be one of the additions to Gspöt2.

(Pinging @DeltaF1 to keep him up to date on the current plans and maybe weigh in)

**Comment by linux-man** [comment]
Please don't apply my sugestion: it breaks collapsegroup option and text selection. It's better to leave the code as it is and stick with the plan
.

**Comment by pgimeno** [comment]
Well, I have good and bad news.

On the bad news side, things are worse than I thought. Gspöt's original author seems to opine that it's OK for elements to have another element as parent even when it doesn't contain them. The demo does this with the Speak button next to the text input line at the bottom, and with the buttons of the option group "Group 1". It seems that only a scrollbox is supposed to apply clipping to its children.

On the good news side, upon examination of the draw function (which is what decides what's clipped and what isn't, therefore the decision on where the click lies should follow the same rules), I've realized that function `getpos` already does the hard work for us. It returns a scissor value that wasn't being used by the `containspoint` function, but is useful for clipping. So I've modified `withinrect` and `withinradius` to account for the scissor, and passed the scissor to them from `containspoint`. I'm not convinced it's correct as is, especially regarding intersection of scissors, but unless one has two nested scrollboxes, it should be fine.

Please test and report if it's OK.

**Comment by linux-man** [comment]
This looks much better. I would say that this particular bug is corrected. More will come...
